    server {
        listen 443;
        server_name diameter-db.p1sec.fr;

        add_header Strict-Transport-Security max-age=15768000;
        add_header X-Robots-Tag noindex;
        add_header Referrer-Policy no-referrer;

        location / {
            proxy_pass http://127.0.0.1:9999;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host            $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        
        location /.well-known/ {
            root /var/www/html;
        }
    }
}
